import type { Nuxt, NuxtModule } from '@nuxt/schema'
import type { ConvexConfig, ResolvedConvexConfig } from './types/config'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { addComponent, addImports, addPlugin, addTemplate, addTypeTemplate, createResolver, defineNuxtModule } from '@nuxt/kit'
import { consola } from 'consola'
import { defu } from 'defu'
import { join } from 'pathe'
import { version } from '../package.json'
import { formatProjectRelativePath, resolveConvexRoot, resolveStorageServerImportPath, toImportPath } from './internal/convex-paths'

export * from './types/index'

const log = consola.withTag('nuxt:convex')

const rootAutoImports = [
  'useConvexQuery',
  'useConvexQueries',
  'useConvexMutation',
  'useConvexAction',
  'useConvexPaginatedQuery',
  'useConvexAuth',
  'useConvexConnectionState',
] as const

const storageAutoImports = [
  'useConvexStorage',
  'useConvexUpload',
] as const

interface BetterAuthDatabaseProviderDefinition {
  buildDatabaseCode: (ctx: unknown) => string
  setup?: (ctx: unknown) => void | Promise<void>
}

type BetterAuthDatabaseProviders = Record<string, BetterAuthDatabaseProviderDefinition>

const module: NuxtModule<ConvexConfig> = defineNuxtModule<ConvexConfig>({
  meta: {
    name: 'nuxt-convex',
    version,
    configKey: 'convex',
    compatibility: { nuxt: '>=3.0.0' },
  },
  defaults: {
    dir: 'convex',
    storage: false,
    r2: false,
    server: true,
  },
  async onInstall(nuxt) {
    const options = nuxt.options.convex as ConvexConfig | undefined
    if (options?.storage)
      await scaffoldStorageFunctions(nuxt)
  },
  async setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const config = resolveConfig(options)

    nuxt.options.runtimeConfig.public.convex = defu(
      nuxt.options.runtimeConfig.public.convex as Record<string, unknown> | undefined,
      {
        dir: config.dir,
        url: config.url,
        r2: config.r2,
        storage: config.storage,
        server: config.server,
      },
    )

    nuxt.hook('better-auth:database:providers', (providers: BetterAuthDatabaseProviders) => {
      addPlugin(resolve('./runtime/better-auth/plugin'))
      providers.convex = {
        buildDatabaseCode: () => `import { useRuntimeConfig } from '#imports'
import { createConvexHttpAdapter } from 'nuxt-convex/better-auth'
import { api } from '#convex/api'

export function createDatabase() {
  const config = useRuntimeConfig()
  const convexUrl = config.betterAuth?.convexUrl || config.public?.convex?.url
  if (!convexUrl) {
    throw new Error('[nuxt-better-auth] Convex URL not configured. Set auth.database.convexUrl, convex.url, or CONVEX_URL.')
  }
  return createConvexHttpAdapter({ url: convexUrl, api: api.auth })
}
export const db = undefined
`,
        setup: (ctx) => {
          const hookNuxt = (ctx as { nuxt?: Nuxt } | undefined)?.nuxt
          if (!hookNuxt)
            return

          const convexUrl = (hookNuxt.options as { auth?: { database?: { convexUrl?: string } } }).auth?.database?.convexUrl
          if (!convexUrl)
            return

          hookNuxt.options.runtimeConfig.betterAuth = defu(
            (hookNuxt.options.runtimeConfig.betterAuth as Record<string, unknown> | undefined) || {},
            { convexUrl },
          )
        },
      }
    })

    addPlugin(resolve('./runtime/plugin'))
    setupConvexApiAlias(nuxt)
    setupConvexExports(nuxt, resolve)
    setupConvexAdvanced(nuxt, resolve)
    setupInternalStorageRefsRuntime(nuxt)

    if (config.storage) {
      setupConvexStorage(nuxt, resolve)
      await scaffoldStorageFunctions(nuxt)
    }
    else {
      setupStorageRuntimeFallback(nuxt, resolve)
    }

    if (config.r2)
      setupConvexR2(nuxt, resolve)

    if (nuxt.options.dev)
      addConvexDevTools(nuxt, config)

    nuxt.hook('ready', () => {
      if (config.url)
        log.info(`Convex connected: ${config.url}`)
      else
        log.warn('Convex URL not configured. Set CONVEX_URL or NUXT_PUBLIC_CONVEX_URL')
    })
  },
})

export default module

function resolveConfig(options: ConvexConfig): ResolvedConvexConfig {
  const url = options.url
    || process.env.CONVEX_URL
    || process.env.NUXT_PUBLIC_CONVEX_URL
    || ''

  return defu(options, { url, dir: 'convex', storage: false, r2: false, server: true }) as ResolvedConvexConfig
}

function setupConvexExports(nuxt: Nuxt, resolve: (path: string) => string): void {
  const convexVueRuntimeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'convex'), 'index')
  const convexVueTypeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'types'), 'index')
  const template = addTemplate({
    filename: 'convex/index.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export * from '${convexVueRuntimeImport}'
`,
    write: true,
  })

  addTypeTemplate({
    filename: 'types/convex.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex' {
  export * from '${convexVueTypeImport}'
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex'] = template.dst

  addImports(rootAutoImports.map(name => ({ name, from: '#convex' })))

  addComponent({ name: 'ConvexQuery', export: 'default', filePath: resolve('./runtime/components/ConvexQuery'), global: true })
  addComponent({ name: 'ConvexPaginatedQuery', export: 'default', filePath: resolve('./runtime/components/ConvexPaginatedQuery'), global: true })

  for (const name of ['ConvexAuthenticated', 'ConvexUnauthenticated', 'ConvexAuthLoading'] as const)
    addComponent({ name, export: name, filePath: resolve('./runtime/components/ConvexAuth'), global: true })
}

function setupConvexAdvanced(nuxt: Nuxt, resolve: (path: string) => string): void {
  const convexVueRuntimeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'convex'), 'advanced')
  const convexVueTypeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'types'), 'advanced')
  const template = addTemplate({
    filename: 'convex/advanced.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export * from '${convexVueRuntimeImport}'
`,
    write: true,
  })

  addTypeTemplate({
    filename: 'types/convex-advanced.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/advanced' {
  export * from '${convexVueTypeImport}'
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex/advanced'] = template.dst
  nuxt.options.alias['#nuxt-convex/advanced-runtime'] = template.dst
}

function setupConvexApiAlias(nuxt: Nuxt): void {
  const convexRoot = resolveConvexRoot(nuxt, (nuxt.options.convex as ConvexConfig | undefined)?.dir || 'convex')
  const generatedDir = convexRoot.generatedDir

  if (!existsSync(generatedDir))
    log.warn(`Missing ${formatProjectRelativePath(nuxt, generatedDir)}. Run \`npx convex dev\` to generate types.`)

  nuxt.options.alias['#convex/api'] = join(generatedDir, 'api')
  const generatedApiImport = toImportPath(join(nuxt.options.buildDir, 'types'), join(generatedDir, 'api'))

  addTypeTemplate({
    filename: 'types/convex-api.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/api' {
  export { api, internal, components } from '${generatedApiImport}'
}
`,
  }, { nitro: true, nuxt: true })
}

function setupConvexStorage(nuxt: Nuxt, resolve: (path: string) => string): void {
  const convexVueRuntimeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'convex'), 'storage')
  const convexVueTypeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'types'), 'storage')
  const template = addTemplate({
    filename: 'convex/storage.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export * from '${convexVueRuntimeImport}'
`,
    write: true,
  })

  addTypeTemplate({
    filename: 'types/convex-storage.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/storage' {
  export * from '${convexVueTypeImport}'
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex/storage'] = template.dst
  nuxt.options.alias['#nuxt-convex/storage-runtime'] = template.dst
  addImports(storageAutoImports.map(name => ({ name, from: '#convex/storage' })))
}

function setupInternalStorageRefsRuntime(nuxt: Nuxt): void {
  const convexRoot = resolveConvexRoot(nuxt, (nuxt.options.convex as ConvexConfig | undefined)?.dir || 'convex')
  const apiPath = join(convexRoot.generatedDir, 'api')
  const generatedApiImport = toImportPath(join(nuxt.options.buildDir, 'convex'), apiPath)
  const template = addTemplate({
    filename: 'convex/storage-refs-runtime.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
import { api } from '${generatedApiImport}'

export function getStorageRefs() {
  return api?._hub?.storage
}
`,
    write: true,
  })

  nuxt.options.alias['#nuxt-convex/storage-refs-runtime'] = template.dst
}

function setupStorageRuntimeFallback(nuxt: Nuxt, resolve: (path: string) => string): void {
  const convexVueRuntimeImport = resolveConvexVueImport(nuxt, resolve, join(nuxt.options.buildDir, 'convex'), 'storage')
  const template = addTemplate({
    filename: 'convex/storage-runtime.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export * from '${convexVueRuntimeImport}'
`,
    write: true,
  })

  nuxt.options.alias['#nuxt-convex/storage-runtime'] = template.dst
}

function resolveConvexVueImport(
  nuxt: Nuxt,
  resolve: (path: string) => string,
  fromDir: string,
  entry: 'advanced' | 'index' | 'storage',
): string {
  const localSourceEntry = resolve(`../../vue/src/${entry}`)
  if (existsSync(localSourceEntry) || existsSync(`${localSourceEntry}.ts`) || existsSync(`${localSourceEntry}.js`))
    return toImportPath(fromDir, localSourceEntry)

  return entry === 'index' ? '@onmax/convex-vue' : `@onmax/convex-vue/${entry}`
}

async function scaffoldStorageFunctions(nuxt: Nuxt): Promise<void> {
  const convexRoot = resolveConvexRoot(nuxt, (nuxt.options.convex as ConvexConfig | undefined)?.dir || 'convex')
  const storageDir = join(convexRoot.writeDir, '_hub')
  const storagePath = join(storageDir, 'storage.ts')
  const generatedServerImport = resolveStorageServerImportPath(convexRoot)

  if (existsSync(storagePath))
    return

  if (convexRoot.fallsBackToProjectWrite) {
    log.warn(`Reading Convex files from ${formatProjectRelativePath(nuxt, convexRoot.readDir)} and scaffolding ${formatProjectRelativePath(nuxt, storagePath)} instead because the resolved layer is not writable. Set \`convex.dir\` to a writable project path to override this.`)
  }

  await mkdir(storageDir, { recursive: true })
  await writeFile(storagePath, `// Auto-generated by nuxt-convex - feel free to customize
import { v } from 'convex/values'
import { mutation, query } from '${generatedServerImport}'

export const generateUploadUrl = mutation(async (ctx) => {
  return await ctx.storage.generateUploadUrl()
})

export const getUrl = query({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    return await ctx.storage.getUrl(storageId)
  },
})

export const remove = mutation({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    await ctx.storage.delete(storageId)
  },
})
`)
  log.success(`Created ${formatProjectRelativePath(nuxt, storagePath)}`)
}

function setupConvexR2(nuxt: Nuxt, resolve: (path: string) => string): void {
  addImports({ name: 'useConvexR2Upload', from: resolve('./runtime/composables/useConvexR2Upload') })
}

interface DevToolsCustomTab {
  name: string
  title: string
  icon?: string
  category?: string
  view: { type: 'iframe', src: string }
}

function addConvexDevTools(nuxt: Nuxt, config: ResolvedConvexConfig): void {
  nuxt.hook('devtools:customTabs', (tabs: DevToolsCustomTab[]) => {
    if (!config.url)
      return

    const dashboardUrl = config.url.replace('.convex.cloud', '.convex.dev')

    tabs.push({
      category: 'server',
      name: 'convex',
      title: 'Convex',
      icon: 'i-simple-icons-convex',
      view: { type: 'iframe', src: dashboardUrl },
    })
  })
}
