import type { Nuxt } from '@nuxt/schema'
import type { ConvexConfig, ResolvedConvexConfig } from './types/config'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { addComponent, addImports, addPlugin, addTemplate, addTypeTemplate, createResolver, defineNuxtModule } from '@nuxt/kit'
import { consola } from 'consola'
import { defu } from 'defu'
import { join } from 'pathe'
import { version } from '../package.json'

const log = consola.withTag('nuxt:convex')

export default defineNuxtModule<ConvexConfig>({
  meta: {
    name: 'nuxt-convex',
    version,
    configKey: 'convex',
    compatibility: { nuxt: '>=3.0.0' },
  },
  defaults: {
    storage: false,
    server: true,
  },
  async onInstall(nuxt) {
    const options = nuxt.options.convex as ConvexConfig | undefined
    if (options?.storage)
      await scaffoldStorageFunctions(nuxt)
  },
  async setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const config = resolveConfig(options)

    nuxt.options.runtimeConfig.public.convex = defu(
      nuxt.options.runtimeConfig.public.convex as Record<string, unknown> | undefined,
      {
        url: config.url,
        storage: config.storage,
        server: config.server,
      },
    )

    addPlugin(resolve('./runtime/plugin'))
    setupConvexApiAlias(nuxt)
    setupConvexExports(nuxt, resolve)

    if (config.storage) {
      setupConvexStorageRefs(nuxt)
      await scaffoldStorageFunctions(nuxt)
    }

    if (nuxt.options.dev)
      addConvexDevTools(nuxt, config)

    nuxt.hook('ready', () => {
      if (config.url)
        log.info(`Convex connected: ${config.url}`)
      else
        log.warn('Convex URL not configured. Set CONVEX_URL or NUXT_PUBLIC_CONVEX_URL')
    })
  },
})

function resolveConfig(options: ConvexConfig): ResolvedConvexConfig {
  const url = options.url
    || process.env.CONVEX_URL
    || process.env.NUXT_PUBLIC_CONVEX_URL
    || ''

  return defu(options, { url, storage: false, server: true }) as ResolvedConvexConfig
}

function setupConvexExports(nuxt: Nuxt, resolve: (path: string) => string): void {
  const template = addTemplate({
    filename: 'convex/index.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export * from '@onmax/convex-vue'
`,
    write: true,
  })

  addTypeTemplate({
    filename: 'types/convex.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex' {
  export * from '@onmax/convex-vue'
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex'] = template.dst

  addImports([
    { name: 'useConvexClient', from: '#convex' },
    { name: 'useConvexQuery', from: '#convex' },
    { name: 'useConvexMutation', from: '#convex' },
    { name: 'useConvexAction', from: '#convex' },
    { name: 'useConvexPaginatedQuery', from: '#convex' },
    { name: 'useConvexStorage', from: '#convex' },
    { name: 'useConvexUpload', from: '#convex' },
  ])

  addComponent({ name: 'ConvexQuery', export: 'default', filePath: resolve('./runtime/components/ConvexQuery'), global: true })
  addComponent({ name: 'ConvexPaginatedQuery', export: 'default', filePath: resolve('./runtime/components/ConvexPaginatedQuery'), global: true })
}

function setupConvexApiAlias(nuxt: Nuxt): void {
  const generatedDir = join(nuxt.options.rootDir, 'convex/_generated')

  if (!existsSync(generatedDir))
    log.warn('convex/_generated not found. Run `npx convex dev` to generate types.')

  nuxt.options.alias['#convex/api'] = join(generatedDir, 'api')

  addTypeTemplate({
    filename: 'types/convex-api.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/api' {
  export * from '../../convex/_generated/api'
}
`,
  }, { nitro: true, nuxt: true })
}

function setupConvexStorageRefs(nuxt: Nuxt): void {
  const apiPath = join(nuxt.options.rootDir, 'convex/_generated/api')
  const hasGeneratedApi = existsSync(`${apiPath}.ts`) || existsSync(`${apiPath}.js`) || existsSync(apiPath)
  const template = addTemplate({
    filename: 'convex/storage-refs.mjs',
    getContents: () => hasGeneratedApi
      ? `// Auto-generated by nuxt-convex
import { api } from ${JSON.stringify(apiPath)}

export const storageRefs = api?._hub?.storage
`
      : `// Auto-generated by nuxt-convex
export const storageRefs = undefined
`,
    write: true,
  })

  nuxt.options.alias['#convex/storage-refs'] = template.dst
}

async function scaffoldStorageFunctions(nuxt: Nuxt): Promise<void> {
  const storageDir = join(nuxt.options.rootDir, 'convex', '_hub')
  const storagePath = join(storageDir, 'storage.ts')

  if (existsSync(storagePath))
    return

  await mkdir(storageDir, { recursive: true })
  await writeFile(storagePath, `// Auto-generated by nuxt-convex - feel free to customize
import { v } from 'convex/values'
import { mutation, query } from '../_generated/server'

export const generateUploadUrl = mutation(async (ctx) => {
  return await ctx.storage.generateUploadUrl()
})

export const getUrl = query({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    return await ctx.storage.getUrl(storageId)
  },
})

export const remove = mutation({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    await ctx.storage.delete(storageId)
  },
})
`)
  log.success('Created convex/_hub/storage.ts')
}

interface DevToolsCustomTab {
  name: string
  title: string
  icon?: string
  category?: string
  view: { type: 'iframe', src: string }
}

function addConvexDevTools(nuxt: Nuxt, config: ResolvedConvexConfig): void {
  nuxt.hook('devtools:customTabs', (tabs: DevToolsCustomTab[]) => {
    if (!config.url)
      return

    const dashboardUrl = config.url.replace('.convex.cloud', '.convex.dev')

    tabs.push({
      category: 'server',
      name: 'convex',
      title: 'Convex',
      icon: 'i-simple-icons-convex',
      view: { type: 'iframe', src: dashboardUrl },
    })
  })
}

export * from './types/config'
