shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - docs

patchedDependencies:
  '@onmax/nuxt-better-auth@0.0.2-alpha.16': patches/@onmax__nuxt-better-auth@0.0.2-alpha.16.patch
  unenv@2.0.0-rc.24: patches/unenv@2.0.0-rc.24.patch
catalog:
  '@nuxt/content': ^3.10.0
  '@nuxt/fonts': ^0.12.1
  '@nuxt/ui': ^4.3.0
  '@vercel/analytics': ^1.6.1
  '@vercel/speed-insights': ^1.3.1
  bumpp: ^10.3.2
  docus: ^5.4.2
  nuxt: ^4.2.2
  tailwindcss: ^4.0.0
  yaml: ^2.8.2

catalogs:
  build:
    '@nuxt/module-builder': ^1.0.2
    typescript: ^5.9.3
  convex:
    '@convex-dev/better-auth': ^0.10.10
    convex: ^1.31.3
  lint:
    '@antfu/eslint-config': ^6.7.3
    '@nuxt/eslint-config': ^1.12.1
    eslint: ^9.39.2
    eslint-plugin-format: ^1.2.0
  nuxt:
    '@nuxt/devtools': ^3.1.1
    vue: ^3.5.26
  playground:
    '@nuxthub/core': ^0.10.3
    '@onmax/nuxt-better-auth': ^0.0.2-alpha.16
    better-auth: 1.4.9
    wrangler: ^4.0.0
  prod:
    '@nuxt/kit': ^4.2.2
    consola: ^3.4.2
    defu: ^6.1.4
    pathe: ^2.0.3
  test:
    '@nuxt/test-utils': ^3.23.0
    '@vue/test-utils': ^2.4.6
    vitest: ^4.0.16
    vitest-package-exports: ^1.1.2
  types:
    '@types/node': ^25.0.5

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
