shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
  - playground
  - docs
  - examples/*

overrides:
  chokidar: 4.0.1

catalog:
  '@nuxt/content': ^3.12.0
  '@nuxt/fonts': ^0.14.0
  '@nuxt/ui': ^4.5.1
  '@vercel/analytics': ^2.0.1
  '@vercel/speed-insights': ^2.0.0
  '@vueuse/core': ^14.2.1
  bumpp: ^11.0.1
  docus: ^5.8.1
  nuxt: 4.4.2
  ofetch: ^1.5.1
  tailwindcss: ^4.2.2
  ufo: ^1.6.3
  yaml: ^2.8.3
  zod: ^4.3.6
  zod-to-json-schema: ^3.25.1

catalogs:
  build:
    '@nuxt/module-builder': ^1.0.2
    publint: ^0.3.12
    tsdown: ^0.21.4
    typescript: ^5.9.3
  convex:
    '@convex-dev/better-auth': ^0.11.3
    '@convex-dev/r2': ^0.9.1
    convex: ^1.34.0
  lint:
    '@antfu/eslint-config': ^7.7.3
    '@nuxt/eslint-config': ^1.15.2
    eslint: ^9.39.4
    eslint-plugin-format: ^2.0.1
  nuxt:
    '@nuxt/devtools': ^3.2.4
    vue: ^3.5.30
  playground:
    '@nuxthub/core': ^0.10.7
    '@onmax/nuxt-better-auth': 0.0.2-alpha.31
    better-auth: 1.5.6
    wrangler: 4.76.0
  prod:
    '@nuxt/kit': 4.4.2
    consola: ^3.4.2
    defu: ^6.1.4
    pathe: ^2.0.3
  test:
    '@nuxt/test-utils': 4.0.0
    '@vue/test-utils': ^2.4.6
    jsdom: ^29.0.1
    vitest: ^4.1.0
    vitest-package-exports: ^1.2.0
  types:
    '@types/node': ^25.5.0

  vite:
    '@vitejs/plugin-vue': ^6.0.5
    vite: ^7.3.1
onlyBuiltDependencies:
  - better-sqlite3
  - sharp
