packages:
  - playground
  - docs

catalog:
  yaml: ^2.8.2

catalogs:
  build:
    '@nuxt/module-builder': latest
    typescript: ^5.0.0
  convex:
    '@convex-vue/core': latest
    convex: latest
  lint:
    '@antfu/eslint-config': ^4.13.2
    '@nuxt/eslint-config': ^1.12.1
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
  nuxt:
    '@nuxt/devtools': latest
    nuxt: ^4.0.0
    vue: latest
  playground:
    '@nuxt/ui': ^4.0.0
    '@nuxthub/core': ^0.10.3
    '@onmax/nuxt-better-auth': https://pkg.pr.new/onmax/nuxt-better-auth/@onmax/nuxt-better-auth@5f06fbf
    better-auth: ^1.4.7
    wrangler: ^4.0.0
  prod:
    '@nuxt/kit': ^4.0.0
    consola: ^3.4.0
    defu: ^6.1.4
    pathe: ^2.0.0
  test:
    '@nuxt/test-utils': latest
    vitest: ^3.2.0
    vitest-package-exports: ^0.1.1
  types:
    '@types/node': ^22.0.0
