import type { Nuxt } from '@nuxt/schema'
import type { ConvexConfig, ResolvedConvexConfig } from './types/config'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { addImportsDir, addPlugin, addTemplate, addTypeTemplate, createResolver, defineNuxtModule } from '@nuxt/kit'
import { consola } from 'consola'
import { defu } from 'defu'
import { join } from 'pathe'
import { version } from '../package.json'

const log = consola.withTag('nuxt:convex')

export default defineNuxtModule<ConvexConfig>({
  meta: {
    name: 'nuxt-convex',
    version,
    configKey: 'convex',
    compatibility: { nuxt: '>=3.0.0' },
  },
  defaults: {
    storage: false,
  },
  async onInstall(nuxt) {
    // One-time setup: scaffold storage functions if storage enabled
    const options = nuxt.options.convex as ConvexConfig | undefined
    if (options?.storage) {
      await scaffoldStorageFunctions(nuxt)
    }
  },
  async setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const config = resolveConfig(options)

    // Expose to runtime config using defu to not overwrite user config
    nuxt.options.runtimeConfig.public.convex = defu(
      nuxt.options.runtimeConfig.public.convex as Record<string, unknown> | undefined,
      { url: config.url },
    )

    // Add plugin to initialize Convex Vue (client-only)
    addPlugin({ src: resolve('./runtime/plugin.client'), mode: 'client' })

    // Add composables auto-imports
    addImportsDir(resolve('./runtime/composables'))

    // Setup virtual module #convex
    setupConvexClient(nuxt, resolve)

    // Setup storage if enabled
    if (config.storage) {
      await setupConvexStorage(nuxt, resolve)
    }

    // DevTools integration
    if (nuxt.options.dev) {
      addConvexDevTools(nuxt, config)
    }

    // Log after ready
    nuxt.hook('ready', () => {
      if (config.url) {
        log.info(`Convex connected: ${config.url}`)
      }
      else {
        log.warn('Convex URL not configured. Set CONVEX_URL or NUXT_PUBLIC_CONVEX_URL')
      }
    })
  },
})

function resolveConfig(options: ConvexConfig): ResolvedConvexConfig {
  const url = options.url
    || process.env.CONVEX_URL
    || process.env.NUXT_PUBLIC_CONVEX_URL
    || ''

  return defu(options, { url, storage: false }) as ResolvedConvexConfig
}

function setupConvexClient(nuxt: Nuxt, _resolve: (path: string) => string): void {
  // Generate virtual module for #convex
  const template = addTemplate({
    filename: 'convex/client.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export { useConvexQuery, useConvexMutation, useConvexAction } from '@convex-vue/core'
`,
    write: true,
  })

  // Type definitions
  addTypeTemplate({
    filename: 'types/convex.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex' {
  export { useConvexQuery, useConvexMutation, useConvexAction } from '@convex-vue/core'
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex'] = template.dst
}

async function setupConvexStorage(nuxt: Nuxt, resolve: (path: string) => string): Promise<void> {
  // Generate virtual module for #convex/storage
  const template = addTemplate({
    filename: 'convex/storage.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export { useConvexStorage } from '${resolve('./runtime/composables/useConvexStorage')}'
`,
    write: true,
  })

  // Type definitions
  addTypeTemplate({
    filename: 'types/convex-storage.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/storage' {
  import type { Ref } from 'vue'

  export interface ConvexStorageReturn {
    generateUploadUrl: () => Promise<string>
    getUrl: (storageId: string) => Ref<string | null>
    remove: (storageId: string) => Promise<void>
  }

  export function useConvexStorage(): ConvexStorageReturn
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex/storage'] = template.dst

  // Auto-scaffold convex/_hub/storage.ts if it doesn't exist
  await scaffoldStorageFunctions(nuxt)
}

async function scaffoldStorageFunctions(nuxt: Nuxt): Promise<void> {
  const storageDir = join(nuxt.options.rootDir, 'convex', '_hub')
  const storagePath = join(storageDir, 'storage.ts')

  if (existsSync(storagePath))
    return

  await mkdir(storageDir, { recursive: true })
  await writeFile(storagePath, `// Auto-generated by nuxt-convex - feel free to customize
import { mutation, query } from '../_generated/server'
import { v } from 'convex/values'

export const generateUploadUrl = mutation(async (ctx) => {
  return await ctx.storage.generateUploadUrl()
})

export const getUrl = query({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    return await ctx.storage.getUrl(storageId)
  },
})

export const remove = mutation({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    await ctx.storage.delete(storageId)
  },
})
`)
  log.success('Created convex/_hub/storage.ts')
}

function addConvexDevTools(nuxt: Nuxt, config: ResolvedConvexConfig): void {
  nuxt.hook('devtools:customTabs', (tabs: any[]) => {
    if (!config.url)
      return

    // Convert deployment URL to dashboard URL
    const dashboardUrl = config.url.replace('.convex.cloud', '.convex.dev')

    tabs.push({
      category: 'server',
      name: 'convex',
      title: 'Convex',
      icon: 'i-simple-icons-convex',
      view: { type: 'iframe', src: dashboardUrl },
    })
  })
}

export * from './types/config'
