import type { Nuxt } from '@nuxt/schema'
import type { ConvexConfig, ResolvedConvexConfig } from './types/config'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { addComponent, addImports, addPlugin, addTemplate, addTypeTemplate, createResolver, defineNuxtModule } from '@nuxt/kit'
import { consola } from 'consola'
import { defu } from 'defu'
import { join } from 'pathe'
import { version } from '../package.json'

const log = consola.withTag('nuxt:convex')

export default defineNuxtModule<ConvexConfig>({
  meta: {
    name: 'nuxt-convex',
    version,
    configKey: 'convex',
    compatibility: { nuxt: '>=3.0.0' },
  },
  defaults: {
    storage: false,
  },
  async onInstall(nuxt) {
    const options = nuxt.options.convex as ConvexConfig | undefined
    if (options?.storage) {
      await scaffoldStorageFunctions(nuxt)
    }
  },
  async setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const config = resolveConfig(options)

    // defu preserves user-defined config
    nuxt.options.runtimeConfig.public.convex = defu(
      nuxt.options.runtimeConfig.public.convex as Record<string, unknown> | undefined,
      { url: config.url },
    )

    addPlugin({ src: resolve('./runtime/plugin.client'), mode: 'client' })

    // Auto-import composables
    addImports([
      { name: 'useConvexUpload', from: resolve('./runtime/composables/useConvexUpload') },
    ])

    // More specific alias must be registered first to avoid #convex matching #convex/api
    setupConvexApiAlias(nuxt)
    setupConvexClient(nuxt, resolve)

    if (config.storage) {
      await setupConvexStorage(nuxt, resolve)
    }

    if (nuxt.options.dev) {
      addConvexDevTools(nuxt, config)
    }

    nuxt.hook('ready', () => {
      if (config.url) {
        log.info(`Convex connected: ${config.url}`)
      }
      else {
        log.warn('Convex URL not configured. Set CONVEX_URL or NUXT_PUBLIC_CONVEX_URL')
      }
    })
  },
})

function resolveConfig(options: ConvexConfig): ResolvedConvexConfig {
  const url = options.url
    || process.env.CONVEX_URL
    || process.env.NUXT_PUBLIC_CONVEX_URL
    || ''

  return defu(options, { url, storage: false }) as ResolvedConvexConfig
}

function setupConvexClient(nuxt: Nuxt, resolve: (path: string) => string): void {
  const template = addTemplate({
    filename: 'convex/client.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export { getConvexClient as useConvex } from '${resolve('./runtime/client')}'
export { useConvexMutation } from '@convex-vue/core'
export { useConvexAction } from '${resolve('./runtime/composables/useConvexAction')}'
export { useConvexQuery } from '${resolve('./runtime/composables/useConvexQuery')}'
export { useConvexPaginatedQuery } from '@convex-vue/core'
`,
    write: true,
  })

  addTypeTemplate({
    filename: 'types/convex.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
import type { ConvexClient, OptimisticUpdate } from 'convex/browser'
import type { FunctionReference, FunctionArgs, FunctionReturnType } from 'convex/server'
import type { AsyncData, AsyncDataOptions } from 'nuxt/app'
import type { MaybeRefOrGetter, Ref } from 'vue'

declare module '#convex' {
  export { useConvexPaginatedQuery } from '@convex-vue/core'

  export interface UseConvexMutationOptions<Mutation extends FunctionReference<'mutation'>> {
    onSuccess?: (data: FunctionReturnType<Mutation>) => void
    onError?: (err: Error) => void
    optimisticUpdate?: OptimisticUpdate<FunctionArgs<Mutation>>
  }

  export interface UseConvexMutationReturn<Mutation extends FunctionReference<'mutation'>> {
    isLoading: Ref<boolean>
    error: Ref<Error | null>
    mutate: (args: FunctionArgs<Mutation>) => Promise<FunctionReturnType<Mutation> | undefined>
  }

  export function useConvexMutation<Mutation extends FunctionReference<'mutation'>>(
    mutation: Mutation,
    options?: UseConvexMutationOptions<Mutation>
  ): UseConvexMutationReturn<Mutation>

  export interface UseConvexActionReturn<Action extends FunctionReference<'action'>> {
    isLoading: Ref<boolean>
    error: Ref<Error | null>
    execute: (args: FunctionArgs<Action>) => Promise<FunctionReturnType<Action>>
  }

  export function useConvexAction<Action extends FunctionReference<'action'>>(
    action: Action
  ): UseConvexActionReturn<Action>

  export interface UseConvexQueryOptions<T> extends Omit<AsyncDataOptions<T>, 'transform' | 'default'> {
    ssr?: boolean
  }

  export function useConvexQuery<Query extends FunctionReference<'query'>>(
    query: Query,
    args: MaybeRefOrGetter<FunctionArgs<Query>>,
    options?: UseConvexQueryOptions<FunctionReturnType<Query>>
  ): Promise<AsyncData<FunctionReturnType<Query> | null, Error | null>>

  export function useConvex(): ConvexClient
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex'] = template.dst

  // Auto-import core composables so users don't need manual imports
  addImports([
    { name: 'useConvexQuery', from: '#convex' },
    { name: 'useConvexMutation', from: '#convex' },
    { name: 'useConvexAction', from: '#convex' },
    { name: 'useConvex', from: '#convex' },
    { name: 'useConvexPaginatedQuery', from: '#convex' },
  ])

  // Auto-import renderless components
  addComponent({ name: 'ConvexQuery', export: 'ConvexQuery', filePath: '@convex-vue/core', global: true })
  addComponent({ name: 'ConvexPaginatedQuery', export: 'ConvexPaginatedQuery', filePath: '@convex-vue/core', global: true })
}

function setupConvexApiAlias(nuxt: Nuxt): void {
  const generatedDir = join(nuxt.options.rootDir, 'convex/_generated')

  if (!existsSync(generatedDir)) {
    log.warn('convex/_generated not found. Run `npx convex dev` to generate types.')
  }

  nuxt.options.alias['#convex/api'] = join(generatedDir, 'api')

  addTypeTemplate({
    filename: 'types/convex-api.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/api' {
  export * from '../../convex/_generated/api'
}
`,
  }, { nitro: true, nuxt: true })
}

async function setupConvexStorage(nuxt: Nuxt, resolve: (path: string) => string): Promise<void> {
  const template = addTemplate({
    filename: 'convex/storage.mjs',
    getContents: () => `// Auto-generated by nuxt-convex
export { useConvexStorage } from '${resolve('./runtime/composables/useConvexStorage')}'
`,
    write: true,
  })

  addTypeTemplate({
    filename: 'types/convex-storage.d.ts',
    getContents: () => `// Auto-generated by nuxt-convex
declare module '#convex/storage' {
  import type { Ref } from 'vue'

  export interface ConvexStorageReturn {
    generateUploadUrl: () => Promise<string>
    getUrl: (storageId: string) => Ref<string | null>
    remove: (storageId: string) => Promise<void>
  }

  export function useConvexStorage(): ConvexStorageReturn
}
`,
  }, { nitro: true, nuxt: true })

  nuxt.options.alias['#convex/storage'] = template.dst

  // Auto-import useConvexStorage when storage is enabled
  addImports({ name: 'useConvexStorage', from: '#convex/storage' })

  await scaffoldStorageFunctions(nuxt)
}

async function scaffoldStorageFunctions(nuxt: Nuxt): Promise<void> {
  const storageDir = join(nuxt.options.rootDir, 'convex', '_hub')
  const storagePath = join(storageDir, 'storage.ts')

  if (existsSync(storagePath))
    return

  await mkdir(storageDir, { recursive: true })
  await writeFile(storagePath, `// Auto-generated by nuxt-convex - feel free to customize
import { mutation, query } from '../_generated/server'
import { v } from 'convex/values'

export const generateUploadUrl = mutation(async (ctx) => {
  return await ctx.storage.generateUploadUrl()
})

export const getUrl = query({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    return await ctx.storage.getUrl(storageId)
  },
})

export const remove = mutation({
  args: { storageId: v.id('_storage') },
  handler: async (ctx, { storageId }) => {
    await ctx.storage.delete(storageId)
  },
})
`)
  log.success('Created convex/_hub/storage.ts')
}

interface DevToolsCustomTab {
  name: string
  title: string
  icon?: string
  category?: string
  view: { type: 'iframe', src: string }
}

function addConvexDevTools(nuxt: Nuxt, config: ResolvedConvexConfig): void {
  nuxt.hook('devtools:customTabs', (tabs: DevToolsCustomTab[]) => {
    if (!config.url)
      return

    const dashboardUrl = config.url.replace('.convex.cloud', '.convex.dev')

    tabs.push({
      category: 'server',
      name: 'convex',
      title: 'Convex',
      icon: 'i-simple-icons-convex',
      view: { type: 'iframe', src: dashboardUrl },
    })
  })
}

export * from './types/config'
