name: release

permissions:
  id-token: write
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-pnpm
      - run: pnpm validate:packages

      - name: GitHub Release
        run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @onmax/convex-vue
        env:
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_ACCESS: public
        run: pnpm --filter @onmax/convex-vue publish --no-git-checks --provenance --access public

      - name: Publish nuxt-convex
        env:
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_ACCESS: public
        run: pnpm --filter nuxt-convex publish --no-git-checks --provenance --access public
